version: "2"
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=assolutions
